### ISSUE TITLE
WebKnight Flashlights and Headlamps Compatibility

### ISSUE THREAD

**Issue by xxthesilentwatcherxx** [DartRuffian/Mine-Detector-Fixes#17]
## Mod
[WebKnight Flashlights and Headlamps](https://steamcommunity.com/sharedfiles/filedetails/?id=2572487482)

### Additional Info
Went through the process of testing it to see which item in our modset was causing the issue.
1) Emptied entire kit into box.
2) Saw the mine with just a mine detector nothing else.
3) Put one item at a time back into the kit until we stopped hearing the mine.
4) Took item back out and then put everything else back into the kit. (mine showed up after removing the headlamp then disappeared when headlamp was re added)

## Items
The following items break mine detectors.
- `WBK_HeadLampItem`

**Comment by DartRuffian** [comment]
Not sure why I never got any notifications on GitHub that issues were opened. I can make a compat next week or so, as I'm currently finishing college.
