### ISSUE TITLE
 Faces of War Compatibility

### ISSUE THREAD

**Issue by acknowledge14** [DartRuffian/Mine-Detector-Fixes#18]
[Faces of War](https://steamcommunity.com/sharedfiles/filedetails/?id=891433622&tscn=1706951187)

### Additional Info
need fix.

## Items
The following items break mine detectors.
- `fow_i_rangeTables_type97`
- `fow_i_rangeTables_m2`

**Comment by DartRuffian** [comment]
Not sure why I never got any notifications on GitHub that issues were opened. I can make a compat next week or so, as I'm currently finishing college.

**Comment by DartRuffian** [comment]
Will take a bit longer than the other compats, since FOW is such a large mod. Should be able to finish it tonight though.
