### ISSUE TITLE
Zombies and Demons Compatibility

### ISSUE THREAD

**Issue by acknowledge14** [DartRuffian/Mine-Detector-Fixes#19]
## Mod
[Zombies and Demons](http://steamcommunity.com/sharedfiles/filedetails/?id=501966277)

### Additional Info
need fix.

## Items
The following items break mine detectors.
- `RyanZombiesAntiVirusTemporary_Item`
- `RyanZombiesAntiVirusCure_Item`

**Comment by acknowledge14** [comment]
temporal fix
https://steamcommunity.com/sharedfiles/filedetails/?id=3249102405&searchtext=

**Comment by DartRuffian** [comment]
Not sure why I never got any notifications on GitHub that issues were opened. I can make a compat next week or so, as I'm currently finishing college.
