### ISSUE TITLE
Can't launch Arma with Mine Detector Patches loaded

### ISSUE THREAD

**Issue by Kibbins** [DartRuffian/Mine-Detector-Fixes#24]
When starting the game with Mine Detector Patches loaded I am having this issue

![Screenshot 2024-07-26 021328](https://github.com/user-attachments/assets/576480f8-333e-4b6a-b1e7-6454e1bba1da)

Not certain what's causing it.

**Comment by DartRuffian** [comment]
Does this occur when only loading CBA and MDF?
There is no instance of `MDF\Main"` in the latest release, it may be caused by another mod trying to include a file that no longer exists.

**Comment by DartRuffian** [comment]
As far as I can tell, this is not an issue with MDF itself.
If another mod is including a non-existant file from MDF, it is on them to fix it.
